### ISSUE TITLE
Add to ContentDB?

### ISSUE THREAD

**Issue by AntumDeluge** [FsxShader2012/rainbow_ore#6]
I was wondering if you were planning on adding this to [ContentDB](https://content.minetest.net/) & if not, would you be okay if I request that it be added by an editor or add it myself?

**Comment by FsxShader2012** [comment]
Since I'm not actively developing this mod anymore, go for it :D

**Comment by wsor4035** [comment]
https://content.minetest.net/packages/KingSmarty/rainbow_ore/ has been added, soon :tm: we should have @AntumDeluge added as a maintainer to the contentdb package

**Comment by AntumDeluge** [comment]
Screenshots added.

**Comment by wsor4035** [comment]
this issue should be able to be closed as @AntumDeluge has been added as a maintainer

**Comment by AntumDeluge** [comment]
Done. Thank you both @FsxShader2012 & @wsor4035.
